apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: network-ticketing-system
  labels:
    app: network-ticketing-system
spec:
  selector:
    matchLabels:
      app: network-ticketing-system
  endpoints:
  - port: https
    interval: 15s
  namespaceSelector:
    matchNames:
    - microservices


