# This Service manifest defines:
# - a load balancer for pods matching label "app: network-ticketing-system"
# - exposing the application to the public Internet (type:ClusterIP)
# - routes port 80 of the load balancer to the port 8080 of the Pods.
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: $NAME
  labels:
    app: $NAME
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: $NAME
  sessionAffinity: None
  type: ClusterIP

