apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $NAME
  labels:
    app: $NAME
spec:
  selector:
    matchLabels:
      app: $NAME
  endpoints:
  - port: https
    interval: 15s
  namespaceSelector:
    matchNames:
    - microservices
